# Generated by Django 6.0.7 on 2026-07-19 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
                ('available_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_paid', models.FloatField()),
                ('total_before_tax', models.FloatField()),
                ('total_tax_payable', models.FloatField()),
                ('net_price', models.FloatField()),
                ('rounded_net_price', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('balance_denomination_breakdown', models.JSONField(default=dict)),
                ('unresolved_balance', models.FloatField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('available_stocks', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField()),
                ('tax_percentage', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
                ('tax_payable', models.FloatField()),
                ('total_price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
